name: Publish
on:
    push:
        branches:
            - main
        paths:
            - 'quickjs/deno.json'

jobs:
    Publish:
        runs-on: ubuntu-latest
        env:
            working-directory: ./quickjs

        permissions:
            contents: write
            id-token: write

        steps:
            - name: Setup repo
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Run linter
              run: deno lint
              working-directory: ${{ env.working-directory }}

            - name: Run tests
              run: deno test
              working-directory: ${{ env.working-directory }}

            - name: Publish to JSR
              run: deno publish
              working-directory: ${{ env.working-directory }}
